name: Test

source              : ./app/src
destination         : ./app/dist
layouts_dir         : ./_layouts
includes_dir        : ./_includes

defaults:
  - scope:
      path: ""
    values:
      layout: default
